# 云效SDK配置示例
yunxiao:
  # 是否启用云效SDK
  enabled: true
  
  # 云效API网关地址
  gateway-url: https://devops.cn-hangzhou.aliyuncs.com
  
  # 访问密钥ID（建议通过环境变量配置）
  access-key-id: ${YUNXIAO_ACCESS_KEY_ID:your-access-key-id}
  
  # 访问密钥Secret（建议通过环境变量配置）
  access-key-secret: ${YUNXIAO_ACCESS_KEY_SECRET:your-access-key-secret}
  
  # 请求超时时间（毫秒）
  timeout: 30000
  
  # 连接超时时间（毫秒）
  connect-timeout: 10000
  
  # 是否启用SSL验证
  ssl-enabled: true
  
  # 重试次数
  retry-count: 3
  
  # 重试间隔（毫秒）
  retry-interval: 1000

# 日志配置
logging:
  level:
    com.alibaba.cloud.yunxiao: INFO
    root: WARN
